config/routes.rb
ImageSharingService::Application.routes.draw do

  get "comment/new"
  get "comment/delete"
  get "comment/edit"
  get "comment/view"
  get "user/view"
  get "image/view"
  post "image/delete"
  post "image/new"
  post "image/randomize"
  post "image/rate"
  post "user/register"
  post "user/login"
  post "user/logout"
  post "comment/new"
  
  get "home/index"

  root 'home#index'

  post 'user/login' => "user#login", as: 'login'
  post 'user/register' => "user#register", as: 'register'
  post 'user/logout' => "user#logout", as: 'logout'
  post 'image/randomize' => "image#randomize", as: 'randomize'
  post 'image/rate' => "image#rate", as: 'rate'
  post 'image/delete' => "image#delete", as: 'delete'
  post 'comment/new' => "comment#new", as: 'new'
  
  get 'image/:id' => 'image#view'
  get 'user/:id' => 'user#view'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    # Get user reference if session cookie exists
	
	@user = nil
	@img = nil
	@uploaderName = nil
    
	   if(!session[SESSION_ACTIVE_USER].nil?)
           begin
               @user = User.find(session[SESSION_ACTIVE_USER]) # Find the user reference from the id from the session cookie
           rescue
               session[SESSION_ACTIVE_USER] = nil
           end
 	   end
	   
	   # Set image and associated references to be dependent on session cookies
	   
	   if(!session[SESSION_IMAGE].nil?)
           if(Image.exists?(session[SESSION_IMAGE]))
	 	      @img = session[SESSION_IMAGE] # get the image from the session cookies
		      @image = Image.find(session[SESSION_IMAGE]) # get the image reference for the id
		      @uploader = User.find(@image.uploader) # get the uploader of the image
		      @rating = @image.rating # get the image's rating
		      @comments = @image.getAllComments # the comments to be shown should have a foreign key equal to the image that is shown
           end
 	   end
	   
   end
   
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/comments.erb
<H3> Image comments </H2>
<% @comments.each do |f| %>
		<% if User.where("id = ?", f.author).empty? %>
		???
		<% else %>
		<%= link_to User.find(f.author).name, "/user/" + f.author.to_s %>
		<% end %>
		: <%= f.contents %> <br>
	<% end %>

<% if !@user.nil? %>
<%= form_tag(comment_new_path , method: "post") do %>
	<%= hidden_field_tag :image_id, @image.id %>
	<%= hidden_field_tag :user_id, @user.id %>
	
	<hr>
	<H3> Write a comment: </H3>
	<%= text_area_tag(:contents, "Enter message here", size: "30x2") %>
	<%= submit_tag("Reply") %>
<% end %>	
<hr>
<% end %>

app/views/home/index.html.erb
<!-- The main page of the side, various subviews are rendered from this point -->
<!-- Area for flash messages sent by controllers to show up -->
<% if flash[:message] %>
   <i><%= flash[:message] %></i>
 <% end %>
<% if flash[:error] %>
    <font color = "red"> <%= flash[:error] %></font>
<% end %>
<H1> Image Sharing Service </H1>
<!-- Only render this if there if the user is not logged in -->
<%if @user.nil?%>
	<%= render :template => "home/login" %>
<% else %>
<!-- Consequently, if the user is logged in and only if the user is logged in, there should be an option to log out -->
	<%= render :template => "home/logout" %>
	<%= render :template => "home/upload" %>
<% end %>
<%= render :template => "home/register" %>
<%= render :template => "home/randomize" %>

app/views/home/login.erb
<hr>
<H2>Login</H2>
<%= form_tag(user_login_path , method: "post") do %>
	<%= label_tag(:name, "Username:") %><br>
	<%= text_field_tag "name" %><br>
	<%= label_tag(:password, "Password:") %><br>
	<%= password_field_tag(:password)%><br>
	<%= submit_tag("Login") %><br>
<% end %>	
<hr>

app/views/home/logout.erb
<hr>
You are logged in as <%=@user.name%>
<%= form_tag(user_logout_path , method: "post") do %>
	<%= submit_tag("Logout") %><br>
<% end %>
<hr>

app/views/home/randomize.erb
<H2> Image view </H2>

<%= form_tag(image_randomize_path , method: "post") do %>
	<%= submit_tag("Randomize") %><br>
<% end %>
<hr>

<% if(!@img.nil?) %>
<H4><b>
Name: <%= @image.name %><br>
Uploader: <%= link_to @uploader.name, "/user/" + @uploader.id.to_s %> <br>
Rating: <%= @rating %>
</b></H4>
<%= image_tag "/image/" + @img.to_s  %>
<%= render :template => "home/rate" %>
<%= render :template => "home/comments" %>
<% end %>

app/views/home/rate.erb
<hr>
<%= form_tag(image_rate_path , method: "post") do %>
	<%= hidden_field_tag :id, @img %>
	<% (1..10).each do |f| %>
		<%= f %>
		<%= radio_button_tag 'rating', f %>
	<% end %>
	<%= submit_tag("Rate") %>
<% end %>	
<hr>

app/views/home/register.erb
<H2>Register</H2>
<%= form_tag(user_register_path , method: "post") do %>
	<%= label_tag(:name, "Username:") %><br>
	<%= text_field_tag "name" %><br>
	<%= label_tag(:password, "Password:") %><br>
	<%= password_field_tag(:password) %><br>
	<%= submit_tag("Register") %><br>
<% end %>	
<hr>

app/views/home/upload.erb
<H3> Image view </H3>

<%= link_to "View my images", "/user/" + @user.id.to_s %><br><br>
<hr>
<H3> Upload an image </H3>

<%= form_tag(image_new_path, :multipart => true, method: "post") do %>
	<%= label_tag(:name, "File:") %>
	<%= file_field_tag "file" %>
	<%= submit_tag("Submit") %>
<% end %>	
<hr>